### ISSUE TITLE
[Android Bootcamp] Week 2 Project: Google Image Search

### ISSUE THREAD

**Issue by amberved** [amberved/GoogleImageSearch#1]
My app is complete, please review. /cc @codepathreview @codepath. 

I was not able to get the infinite scrolling to work. I need more time to better understand this part. 
I wish you had a the video to cover this concept.

**Comment by nesquena** [comment]
@amberved infinite scrolling is part of the required user stories and is an important part of the homework. Please resubmit with infinite scrolling setup. Check the helpful hints and guides and ask any specific questions you have if you are stuck.

**Comment by amberved** [comment]
still cont. to work on this. Will push changes soon

**Comment by amberved** [comment]
@nesquena 
Wonder why I don't see OnScroll event ... 

in MainActivity.java

private GridView gvResults;
... 
gvResults.setOnScrollListener( new EndlessScrollListener() {
            @Override
            public void onLoadMore(int page, int totalItemsCount) {
                Log.i("GoogleImageSearch", "onLoadMore");
                Toast.makeText(getApplicationContext(),"onScrollListerner",Toast.LENGTH_SHORT).show();
                googleImageSearch();
            }
        });

**Comment by nesquena** [comment]
@amberved this is a special scrolling listener we build that handles the scrolling management internally in the `EndlessScrollListener` class. You can go into that class and look at the onScroll method to see how it works. Instead it only calls `onLoadMore` once it detects you have to load a second set of items.

**Comment by amberved** [comment]
@nesquena ; Thanks for the feedback. I have uploaded the fixes for EndlessScroll

**Comment by nesquena** [comment]
@amberved Great, can you also email me any hints you think I should add to the helpful hints that would have helped you understand faster? Always trying to improve the hints.

**Comment by amberved** [comment]
Sure. I think mainly my issue was with visible threshold and itemcount

Send you something soon proper in sometime. Just headed out with family for
dinner.

Amber
On Feb 15, 2015 6:17 PM, "Nathan Esquenazi" <notifications@github.com> wr

**Comment by nesquena** [comment]
Ok thanks let me know what to add to the hints, a full review of your project will be done later and feedback posted as well.

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:

* Good to see you used a filters object to represent the filters to apply to the query
* Properly used spinners (with populated values) to allow users to select filters
* Consider using the [ViewHolder pattern](https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) to improve performance of photos `GridView`.
* Nice job adding the share intent to the image detail view!
* Nice to see you added the search box to the ActionBar!
* Consider creating a static method in a Helper/Utility class for common methods such as checking for internet (just like you tried with `NetworkStatus`)
* Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
